import 'package:cloud_firestore/cloud_firestore.dart';

final firestoreInstance = FirebaseFirestore.instance;
const String collectionVillageCode = "villageCode";
const String collectionVillageName = "villageName";
const String collectionGender = "gender";
const String collectionRelation = "relationshipFamily";
const String mapRelation = "relationShip";
const String collectionEducation = "education";
const String collectionStatusHouse = "statusHouseType";
const String mapStatusHouse = "statusHouse";
const String collectionTypeHouse = "typeHouse";
const String collectionMaritalStatus = "MaritalStatus";
const String collectionBusiness = "business";
const String collectionBloodGroup = "bloodGroup";
const String collectionSection = "section";
const String mapFamilyMembers = "familyMembers";
const String collectionAnnualIncome = "annualIncome";
const String mapAnnualIncome = "income";
const String collectionCount = "DemographicCount";
